/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Code.Student;
import Code.ConnectionDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Rajitha Shavinda
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void init(String n, String pass) {
     //(initialize) fill user name and password text boxes values
        txtUsername.setText(n);
        txtPassword.setText(pass);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblNewAccount = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Password : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 190, 90, 40);

        jLabel2.setText("User Name : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 130, 90, 40);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername);
        txtUsername.setBounds(290, 140, 170, 30);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(290, 250, 170, 30);

        lblNewAccount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNewAccount.setText("Create new account");
        lblNewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewAccountMouseClicked(evt);
            }
        });
        jPanel1.add(lblNewAccount);
        lblNewAccount.setBounds(290, 350, 210, 30);
        jPanel1.add(txtPassword);
        txtPassword.setBounds(290, 190, 170, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try {
            // call "ConnectionDB" class "Connect()" method to initialize Connection object
            java.sql.Connection con = ConnectionDB.Connect(); 
            
            // get all details from user name
            String sql = "SELECT * FROM `student` WHERE `ID`='" + txtUsername.getText() + "';";
            
            //java.sql.Statement>> 'Statement' object used for executing a static SQL statement and returning the results it produces.
            java.sql.Statement state = con.createStatement();

            //'ResultSet' >> A table of data representing a database result set, which is usually generated by executing a 'Statement' that queries the database.
            ResultSet rs = state.executeQuery(sql);
            
            //it shifts the cursor to the next row of the result set || in this case >> first Row 
            rs.next();
            

            String password = String.valueOf(txtPassword.getPassword());// get password to this variable
            
            String type = rs.getString("type"); // get user type form the table (admin or std )

            if (password.equals(rs.getString("password"))) {//text box password equals to table>>user's record's password 

                if (type.equals("std")) { // user type equals to STD navigate to Student interface otherwise navigate to Admin interface

                    StudentProfile s = new StudentProfile();
                    s.getStudent(txtUsername.getText());
                    s.setVisible(true);

                } else {
                    new ADMIN().setVisible(true);

                }
                this.dispose();
            }else{ // display error message for incorrect user details
            JOptionPane.showMessageDialog(null, "Incorrect login details !");
            }

            rs.close();

        } catch (SQLException se) {
            JOptionPane.showMessageDialog(null, se.getMessage());
            //return null;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            //return null;
        }


    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblNewAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewAccountMouseClicked
        // navigate to Register interface
        Register r = new Register();
        r.setAdmin(false); // go to the interface as Student
        r.setVisible(true); // display interface
        r.setPasswordFields(false); // disable update password option
        this.dispose(); // close this interface
    }//GEN-LAST:event_lblNewAccountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNewAccount;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
