/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Code.ConnectionDB;
import Code.Student;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rajitha Shavinda
 */
public class studentsAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Subjects
     */
    Student std;

    public studentsAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        LoadTbl();

    }

    private void LoadTbl() {
        try {

            //get current table model and clear all 
            DefaultTableModel dm1 = (DefaultTableModel) jTable_student.getModel();
            dm1.getDataVector().removeAllElements();
            dm1.fireTableDataChanged();

            java.sql.Connection con = ConnectionDB.Connect();

            //get all students detail
            String sql = "SELECT * FROM `student` where type='std'";

            //java.sql.Statement>> 'Statement' object used for executing a static SQL statement and returning the results it produces.
            java.sql.Statement state = con.createStatement();

            //'ResultSet' >> A table of data representing a database result set, which is usually generated by executing a 'Statement' that queries the database.
            ResultSet rs = state.executeQuery(sql);

            DefaultTableModel model = (DefaultTableModel) jTable_student.getModel(); //get current table model || table object

            while (rs.next()) {

                //add student details to the table row by row
                model.addRow(new Object[]{rs.getString("ID"), rs.getString("Name"),
                    rs.getString("email"), rs.getString("Contact"), rs.getString("Cname")});

                jTable_student.setModel(model);
            }

            state.close(); //Statement

            rs.close(); // ResultSet

        } catch (SQLException se) {
            JOptionPane.showMessageDialog(null, se.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        //---------------------------------------------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_student = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTable_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Contact", "Course Name"
            }
        ));
        jScrollPane1.setViewportView(jTable_student);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 452, 450);

        jButton1.setText("Add new Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 50, 130, 40);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(470, 110, 130, 40);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(470, 170, 130, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Students");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(140, 0, 320, 40);

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(480, 460, 120, 40);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(480, 410, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Register r = new Register();
        r.setAdmin(true); //go to the interface as admin
        r.setPasswordFields(false); // disable update password option
        r.setVisible(true); // display interface
        this.dispose();// close this interface
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int row = -1;
        String id;
        row = jTable_student.getSelectedRow(); //get select row number

        if (row == -1) {

            JOptionPane.showMessageDialog(null, "Please select an item");

        } else {

            try {

                id = jTable_student.getValueAt(row, 0).toString();//get selected item's id
                java.sql.Connection con = ConnectionDB.Connect();

                //get student details by id
                String sql = "SELECT * FROM `student` where ID='" + id + "'";

                java.sql.Statement state = con.createStatement();

                ResultSet rs = state.executeQuery(sql);

                rs.next();

                //creating Student object using Result set's data
                std = new Student(rs.getString("ID"), rs.getString("Name"), rs.getString("email"),
                        rs.getString("contact"), rs.getString("Cname"), rs.getString("bday"), rs.getString("password"),
                        rs.getString("subjects"), rs.getString("subNames"));

                state.close(); //Statement

                rs.close(); // ResultSet

                Register r = new Register();
                r.init(std, true);//send student objects to "Register" interface
                r.setPasswordFields(true);// enable update password option
                r.setVisible(true);
                this.dispose();

            } catch (SQLException se) {
                JOptionPane.showMessageDialog(null, se.getMessage());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int row = -1;
        String id;
        row = jTable_student.getSelectedRow(); //get select row number

        if (row == -1) {

            JOptionPane.showMessageDialog(null, "Please select an item");

        } else {

            try {
                //get confirmation message's answer to the "dialogButton1" variable (yes || no)
                   int dialogButton1 = JOptionPane.showConfirmDialog(null, "Are you sure you want to permanently delete this record?", "Delete", JOptionPane.YES_NO_OPTION);

                if (dialogButton1 == 0) { //if user click yes

                    

                id = jTable_student.getValueAt(row, 0).toString();//get selected item's id
                
                java.sql.Connection con = ConnectionDB.Connect();
                
                //query: delete student record from the table
                String str = "delete from `student` Where `ID`='" + id + "';";

                Statement statement = con.createStatement();

                statement.executeUpdate(str);//delete

                statement.close();

                JOptionPane.showMessageDialog(null, "Successfull");
                LoadTbl();//Re-load table
                }
            } catch (SQLException se) {
                JOptionPane.showMessageDialog(null, se.getMessage());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new ADMIN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_student;
    // End of variables declaration//GEN-END:variables
}
