/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Code.ConnectionDB;
import Code.Subject;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rajitha Shavinda
 */
public class Subjects extends javax.swing.JFrame {

    /**
     * Creates new form Subjects
     */
    Subject subject;
    
    public Subjects() {
        initComponents();
        setLocationRelativeTo(null);
        LoadTbl();
    }

    private void LoadTbl() {
        try {
            //get current table model and clear all 
            DefaultTableModel dm1 = (DefaultTableModel) jTable.getModel();
            dm1.getDataVector().removeAllElements();
            dm1.fireTableDataChanged();

            // call "ConnectionDB" class "Connect()" method to initialize Connection object
            java.sql.Connection con = ConnectionDB.Connect();

            //query: get all subjects data
            String sql = "SELECT * FROM `subjects`";

            //java.sql.Statement>> 'Statement' object used for executing a static SQL statement and returning the results it produces.
            java.sql.Statement state = con.createStatement();

                        //'ResultSet' >> A table of data representing a database result set, which is usually generated by executing a 'Statement' that queries the database.
            ResultSet rs = state.executeQuery(sql);

            
            DefaultTableModel model = (DefaultTableModel) jTable.getModel();//get current table model || table object

            while (rs.next()) {
                //fill table rows as Subject ID,Name,Key,Description
                model.addRow(new Object[]{rs.getString("sID"), rs.getString("SName"),
                    rs.getString("Key"), rs.getString("Des")});

                jTable.setModel(model);
            }

            state.close(); //Statement

            rs.close(); // ResultSet

        } catch (SQLException se) {
            JOptionPane.showMessageDialog(null, se.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        //---------------------------------------------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtKey = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDes = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject ID", "Subject Name", "Enrolment key ", "Description"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 480, 490);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 370, 200, 30);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(530, 410, 200, 30);

        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(530, 450, 200, 30);
        jPanel1.add(txtKey);
        txtKey.setBounds(530, 220, 200, 30);
        jPanel1.add(txtID);
        txtID.setBounds(530, 80, 200, 30);
        jPanel1.add(txtName);
        txtName.setBounds(530, 150, 200, 30);

        txtDes.setColumns(20);
        txtDes.setRows(5);
        jScrollPane2.setViewportView(txtDes);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(530, 280, 200, 80);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Subjects");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(160, 0, 320, 40);

        jLabel1.setText("Subject Description:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 260, 140, 30);

        jLabel2.setText("Subject ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 50, 140, 30);

        jLabel3.setText("Subject Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(530, 120, 140, 30);

        jLabel4.setText("Enrolment key :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(530, 190, 140, 30);

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(530, 500, 100, 40);

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(640, 500, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // call "ConnectionDB" class "Connect()" method to initialize Connection object
            java.sql.Connection con = ConnectionDB.Connect();
            
            //query: insert new subject details 
            String str = "INSERT INTO `subjects` values('" + txtID.getText() + "','" + txtName.getText() + "','" + txtKey.getText() + "','"
                    + txtDes.getText() + "');";

             //'Statement' object used for executing a static SQL statement and returning the results it produces.
            Statement statement = con.createStatement();

            statement.executeUpdate(str);//Insert

            statement.close();

            JOptionPane.showMessageDialog(null, "Successfull");

            LoadTbl();

        } catch (SQLException se) {
            JOptionPane.showMessageDialog(null, se.getMessage());
            //return null;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            //return null;
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = -1;

        row = jTable.getSelectedRow();//get select row number

        if (row == -1) {

            JOptionPane.showMessageDialog(null, "Please select an item");

        } else {

            String[] arr = new String[4];

             // get selected row details to array
            arr[0] = jTable.getValueAt(row, 0).toString();
            arr[1] = jTable.getValueAt(row, 1).toString();
            arr[2] = jTable.getValueAt(row, 2).toString();
            arr[3] = jTable.getValueAt(row, 3).toString();
            
            subject=new Subject(arr[0],arr[1],arr[2], arr[3]);//creats "Subject" obeject

            SubjectsDetails sd = new SubjectsDetails();

            sd.init(subject); // send "subject" object to "SubjectsDetails" interface
            sd.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = -1;

        row = jTable.getSelectedRow(); //get select row number

        String id = " ";

        if (row == -1) {

            JOptionPane.showMessageDialog(null, "Please select an item");

        } else {
            //get confirmation message's answer to the "dialogButton1" variable (yes || no)
               int dialogButton1 = JOptionPane.showConfirmDialog(null, "Are you sure you want to permanently delete this record?", "Delete", JOptionPane.YES_NO_OPTION);

                if (dialogButton1 == 0) { //if user click yes,

                    
            
            try {
                java.sql.Connection con = ConnectionDB.Connect();
                id = jTable.getValueAt(row, 0).toString();//get selected item's id

                //query: delete item by id
                String str = "delete from `subjects` Where `sID`='" + id + "';";

                Statement statement = con.createStatement();

                statement.executeUpdate(str);//delete

                LoadTbl(); // re-load table

                statement.close();

                JOptionPane.showMessageDialog(null, "Successfull");

            
            } catch (SQLException se) {
                JOptionPane.showMessageDialog(null, se.getMessage());
                //return null;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                //return null;
            }
                }
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new ADMIN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea txtDes;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtKey;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
